# This module provides utilities to generate codes for topics and sections

def generate_topic_code(topic_title: str): 
    """Generates a code for a topic
    
    The code is generated by using the Topic title, removing all non alphanumeric characters (except white spaces) and replacing whistespaces with a dash. 
    
    Args:
        topic_title (str): the title of the topic
    
    Returns:
        str: the code of the topic
    """
    
    # Remove all non alphanumeric characters
    topic_title = ''.join(e for e in topic_title if e.isalnum() or e.isspace())
    
    # Replace all white spaces with a dash
    topic_title = topic_title.replace(' ', '-')
    
    return topic_title.lower()

def generate_section_code(section_title: str): 
    """Generates a code for a section
    
    The code is generated by using the Section title, removing all non alphanumeric characters (except white spaces) and replacing whistespaces with a dash. 
    
    Args:
        section_title (str): the title of the section
    
    Returns:
        str: the code of the section
    """
    
    # Remove all non alphanumeric characters
    section_title = ''.join(e for e in section_title if e.isalnum() or e.isspace())
    
    # Replace all white spaces with a dash
    section_title = section_title.replace(' ', '-')
    
    return section_title.lower()